name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: '1.19'

    - name: Install libpcap-dev
      run: sudo apt-get update && sudo apt-get install -y libpcap-dev

    - name: Build
      run: |
        export CGO_ENABLED=1
        go build -v ./...

    - name: Test
      run: |
        export CGO_ENABLED=1
        go test -v ./...
